# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/conf.py
   fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

3 python
python:
   version: 3.8
   install:
   - requirements: doc/requirements.txt

# packages
packages:
  path: .
  method: setuptools